In [1]:
import numpy as np
import pandas as pd

In [2]:
#generating 100 random numbers between 1 to 20
x1 = np.random.randint(low=1,high=20,size=(100,))

In [3]:
#generating 100 random numbers between 1 to 20
x2 = np.random.randint(low=1,high=20,size=(100,))

In [4]:
x1

array([ 3,  6,  9, 12, 13, 13, 19,  1, 10, 18,  8,  9,  9,  6, 17, 18, 17,
       17, 12, 17, 17, 14,  7,  7, 10, 10, 15,  5,  7,  1, 19, 17, 18, 18,
       15, 17, 11, 15, 13, 17, 16, 11,  2, 13, 12,  2,  3, 19, 13, 17, 13,
        1, 15,  6, 16,  4, 16, 19,  6, 18,  5,  3, 13, 18, 11,  5, 11,  3,
        8,  3,  4, 11, 11, 11, 16,  7, 14,  4,  7,  3,  2, 19,  3, 17, 14,
        8, 10,  3, 12,  5, 10, 15, 11, 11,  1,  3, 19, 16, 17,  5])

In [5]:
x2

array([ 5, 10, 10,  7,  3,  8,  7,  1,  6,  6,  6, 14, 15,  6, 13, 14,  8,
        4, 13, 11,  6, 15,  6, 19,  3,  4, 19, 19,  7,  4, 17,  7, 19,  1,
        1,  5, 11,  5, 10, 13,  8, 12,  8, 17, 12,  5, 12, 15,  5,  8,  2,
        6, 18, 10,  6, 10, 10, 18,  1, 16, 14,  1, 18,  7, 17, 14, 10,  4,
       14,  8, 18, 12,  6, 15, 16, 11,  1, 19, 15,  3, 10,  2, 11, 14,  3,
        9,  3,  1,  1, 12, 11, 15, 11, 11, 12,  7,  2,  8, 11, 18])

Let's simulate data based on x1 and x2 and use gradient descent and see how close is the co-efficient values estimated by gradient descent algorithm

In [6]:
#generating y values as a linear combination of x1 and x2 along with some noise(random numbers)
y = 3 + 4*x1 - 2*x2 + np.random.random((100,))
# here beta_0 = 3,beta_1 = 4,beta_2 = -2

The simulated data is as per the above formula.Let's pretend that we don't know the co_efficients of x1 and x2 and find the co_efficients of x1 and x2,with the data x1,x2 and y

In [7]:
y

array([ 5.93192140e+00,  7.78273111e+00,  1.95281475e+01,  3.73697871e+01,
        4.94196326e+01,  3.95398776e+01,  6.52189245e+01,  5.83022702e+00,
        3.12527931e+01,  6.33248450e+01,  2.32227108e+01,  1.11194284e+01,
        9.80694362e+00,  1.55749596e+01,  4.53650203e+01,  4.76700399e+01,
        5.58506516e+01,  6.35445508e+01,  2.54571787e+01,  4.97052752e+01,
        5.92700391e+01,  2.92767663e+01,  1.97884844e+01, -6.87908598e+00,
        3.74891331e+01,  3.54791938e+01,  2.57414915e+01, -1.40593869e+01,
        1.78356868e+01, -4.23259429e-01,  4.50361374e+01,  5.77522239e+01,
        3.78818166e+01,  7.33386413e+01,  6.11382815e+01,  6.10227245e+01,
        2.56987305e+01,  5.37862895e+01,  3.58320222e+01,  4.58936659e+01,
        5.19740889e+01,  2.37588136e+01, -4.89718422e+00,  2.19136413e+01,
        2.78822647e+01,  1.47336139e+00, -8.57006389e+00,  4.93584208e+01,
        4.56847129e+01,  5.57439610e+01,  5.14413943e+01, -4.70517243e+00,
        2.70911230e+01,  

In [8]:
X = pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})

In [9]:
X

intercept  x1  x2
0           1   3   5
1           1   6  10
2           1   9  10
3           1  12   7
4           1  13   3
..        ...  ..  ..
95          1   3   7
96          1  19   2
97          1  16   8
98          1  17  11
99          1   5  18

[100 rows x 3 columns]

In [10]:
#initializing the weights(the betas) to zero
w = np.zeros(X.shape[1])

In [11]:
w

array([0., 0., 0.])

In [12]:
#function that takes in features(X) and weights(betas or co_efficients) and return the predicted values(y_hat)
def predictions(features,weights):
    predictions = np.dot(features,weights)
    return predictions

In [13]:
predictions(X,w)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#function that gives the error which the difference between actual and predicted values
def myerror(target,features,weights):
    error = target - predictions(features,weights)
    return error

In [15]:
#function that gives the value of cost function
def cost_function(target,features,weights):
    error = myerror(target,features,weights)
    cost = np.dot(error.T,error)
    return cost

In [16]:
cost_function(y,X,w)

133191.71396994777

In [17]:
#function that gives the value of gradient.Gradient values are the values of derivative of cost function wrt the weights
def gradient(target,features,weights):
    error = myerror(target,features,weights)
    gradient = -np.dot(features.T,error)
    return gradient
    

In [18]:
gradient(y,X,w)

array([ -2757.75475349, -41685.63103964, -21559.15369331])

In [19]:
#function that implements the gradient descent and returns the weights
def estimating_weights(target,features,learning_rate):
    weights = np.zeros(features.shape[1])
    for i in np.arange(100000):
        weights = weights - learning_rate * gradient(target,features,weights)
        if i%1000==0:
            print(cost_function(target,features,weights),weights)
    return(weights)
    
    

In [20]:
estimating_weights(y,X,0.000001)

128821.83807264044 [0.00275775 0.04168563 0.02155915]
352.6278322947163 [ 0.14736727  3.96144691 -1.64826427]
150.23392558539712 [ 0.19024519  4.12610429 -1.84076656]
145.6474024385328 [ 0.23325304  4.13522768 -1.85515542]
142.01993652269172 [ 0.27573813  4.13410851 -1.85776608]
138.49143407172062 [ 0.31766439  4.13233607 -1.85957738]
135.05565777630972 [ 0.35903639  4.13054297 -1.86131425]
131.71015544290088 [ 0.39986127  4.12877068 -1.86302482]
128.4525550837966 [ 0.44014624  4.12702164 -1.86471255]
125.28054710321834 [ 0.47989846  4.12529571 -1.86637794]
122.19188258955674 [ 0.51912496  4.1235926  -1.8680213 ]
119.18437172061658 [ 0.5578327   4.12191202 -1.86964294]
116.25588221106264 [ 0.59602854  4.12025367 -1.87124313]
113.40433780065382 [ 0.63371925  4.11861724 -1.87282215]
110.62771678220537 [ 0.67091151  4.11700246 -1.87438029]
107.92405056822412 [ 0.7076119   4.11540903 -1.87591783]
105.29142229520569 [ 0.74382695  4.11383668 -1.87743503]
102.72796546460505 [ 0.77956305  4.11

array([ 2.56284036,  4.03486026, -1.95364132])

We observe that beta_1 and beta_2 values are close to the actual beta_1 and beta_2  whereas beta_0 is some what deviated from the actual beta_0(which is 3) as we add some noise 

Let's see the co_efficient values estimated using sklearn

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
lr=LinearRegression()

In [23]:
lr.fit(X.iloc[:,1:],y)

LinearRegression()

In [24]:
#co_efficents of x1, x2.,i.e the values of beta_1 ,beta_2
lr.coef_

array([ 3.99651448, -1.9906421 ])

We observe that the beta_1 and beta_2 values are pretty close to the actual beta_1 and beta_2 values

In [25]:
lr.intercept_

3.446034271759107